name: build-binary-package

on:
  release:
    types:
    - prereleased
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main
      
permissions:
  # Use write for: hub release edit
  contents: write

env:
  PROGRAM_NAME: crowdsec-firewall-bouncer

jobs:
  build:
    name: Build and upload all platforms
    runs-on: ubuntu-latest

    steps:

    - name: Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Build mips64 platform
      run: |
        # build platform-all first so the .xz vendor file is not removed
        # @see https://discourse.crowdsec.net/t/quick-how-to-for-firewall-bouncer-on-ubiquity-edgerouter/361
        # 
        export GOOS=linux
        export GOARCH=mips64
        make

    - name: Upload to release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tag_name="${GITHUB_REF##*/}"
        # this will upload the $PROGRAM_NAME-vendor.tar.xz file as well
        gh release upload "$tag_name" $PROGRAM_NAME* vendor.tgz
